server {
    listen       80;
    server_name  localhost;

    access_log  /dev/stdout;
    error_log   /dev/stderr warn;
    
    root   /usr/share/nginx/html;

    # 1. Sposta il proxy in alto e usa ^~ per bloccare il controllo dei file statici (.png)
    location ^~ /badge/ {
        proxy_pass http://127.0.0.1:3001/badge/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_valid 200 1d;
        add_header Cache-Control "public, max-age=86400";
    }

    # File statici
    location ~* \.(js|json|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1h;
        add_header Cache-Control "public, immutable";
    }

    # Root
    location = / {
        try_files /index.html =404;
    }

    # Tutte le altre route
    location / {
        # Redirect a hash solo se non inizia già con /#
        if ($request_uri ~ "^/[^#]") {
            rewrite ^/(.*)$ /#/$1 redirect;
        }
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}