name: Release
on:
  release:
    types: [created]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NEW_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Upgrade version
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          npm version $NEW_VERSION
          git push
      - name: Build and publish a Docker image for $IMAGE_NAME:$NEW_VERSION
        uses: macbre/push-to-ghcr@master
        with:
          image_name: $IMAGE_NAME:$NEW_VERSION  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
